feat: 支持linux天脉集群安装和卸载 --spray-build-ci-cd --kubean-build-ci-cd
Signed-off-by: guiyong.ou <guiyong.ou@daocloud.io>

diff --git a/playbooks/linux-acoreos-master.yml b/playbooks/linux-acoreos-master.yml
--- a/playbooks/linux-acoreos-master.yml
+++ b/playbooks/linux-acoreos-master.yml
@@ -7,9 +7,69 @@
   tasks:
     - name: Install ACoreOs Master
       shell: |
-        /usr/local/bin/kubectl get node -o wide
-        /usr/local/bin/kubectl -n kube-system get pod
-        /usr/local/bin/kubectl get --raw='/readyz?verbose'
+        NODE_NAME=`hostname`
+        ARCH=`uname -m` # aarch64、x86_64
+        # Check Docker
+        echo "1. Check docker exist"
+        which docker > /dev/null
+        if [ $? -ne 0 ]; then
+                echo "ERROR: Please install docker before run install script."
+                exit
+        fi
+        echo "2. Install tools"
+        mkdir -p /usr/local/bin/
+        wget {{ minio_address }}/acoreos/$ARCH/tools.tar
+        wget {{ minio_address }}/acoreos/$ARCH/cni.tar
+        tar -xf tools.tar
+        cp tools/* /usr/local/bin/
+        tar xf cni.tar -C /
+        echo "3. Load images"
+        docker pull {{ registry_host }}/acoreos/cos-master:latest
+        docker pull {{ registry_host }}/acoreos/cos-worknode:latest
+        docker pull {{ registry_host }}/acoreos/cos-dashboard:latest
+        wget {{ minio_address }}/acoreos/$ARCH/pause.tar
+        wget {{ minio_address }}/acoreos/$ARCH/busybox.tar
+        ctr -n k8s.io i import pause.tar
+        ctr -n k8s.io i import busybox.tar
+        echo "4. Generate configs"
+        kubectl config set-cluster cos --server=http://{{ master_host }}
+        kubectl config set-context acorecloudos
+        kubectl config set contexts.acorecloudos.cluster cos
+        kubectl config use-context acorecloudos
+        wget {{ minio_address }}/acoreos/config.tar
+        tar -xf config.tar
+        sed -e "s/REGISTRY_ADDR/{{ registry_host }}/g" configs/config.toml > /etc/containerd/config.toml
+        sed -e "s/REGISTRY_ADDR/{{ registry_host }}/g" configs/daemon.json > /etc/docker/daemon.json
+        cp configs/crictl.yaml /etc/crictl.yaml
+        echo "5. Run containers"
+        docker ps | grep cos- > /dev/null
+        if [ $? -eq 0 ]; then	
+                echo "Stop and remove running containers"
+                docker rm -f cos-master > /dev/null
+                docker rm -f cos-worknode > /dev/null
+                docker rm -f cos-dashboard > /dev/null
+        fi
+        docker run -d --restart=always --network=host --name cos-master {{ registry_host }}/acoreos/cos-master:latest --address=0.0.0.0:8080 --node-monitor-period 300 --node-startup-grace-period 5000 --node-monitor-grace-period 600 --pod-eviction-timeout 100 > /dev/null
+        if [ $? -ne 0 ]; then
+                echo "Run cos-master failed"
+                exit
+        fi
+        echo "Run cos-master success"
+        docker run -itd --restart=always --network=host --privileged=true --name cos-worknode -v /run/containerd/containerd.sock:/containerd/containerd.sock -v /run/flannel:/flannel -v /proxy-root:/proxy-root -v /etc/machine-id:/etc/machine-id {{ registry_host }}/acoreos/cos-worknode:latest --api-servers={{master_host}}:{{master_host}} --hostname-override=$NODE_NAME --enable-pod-ipam=1 --container-runtime-endpoint=unix:///containerd/containerd.sock --node-status-update-frequency=290 --sync-frequency=30000 > /dev/null
+        #--node-ips=$LOCAL_IPS --nic-names=$LOCAL_NIC_NAMES 
+        if [ $? -ne 0 ]; then
+                echo "Run cos-worknode failed"
+                exit
+        fi
+        echo "Run cos-worknode success"
+        docker run -d --restart=always --network=host --name cos-dashboard -e SERVER_HOST={{master_host}}:{{master_host}} {{ registry_host }}/acoreos/cos-dashboard:latest > /dev/null
+        if [ $? -ne 0 ]; then
+                echo "Run cos-dashboard failed"
+                exit
+        fi
+        echo "Run cos-dashboard success"
+        echo "Clean tar"
+        rm -rf tools.tar cni.tar pause.tar busybox.tar config.tar tools config
       args:
         executable: /bin/bash
       register: clusterinfo
diff --git a/playbooks/linux-acoreos-node.yml b/playbooks/linux-acoreos-node.yml
--- a/playbooks/linux-acoreos-node.yml
+++ b/playbooks/linux-acoreos-node.yml
@@ -10,43 +10,46 @@
   tasks:
     - name: Install ACoreOs Node
       shell: |
-        hostname
-        echo "- HostName: {{ ansible_hostname }}"
-        echo "- Master: {{ master_host }}:{{ master_port }}"
+        NODE_NAME=`hostname`
+        ARCH=`uname -m` # aarch64、x86_64
+        # Check Docker
         echo "1. Check docker exist"
         which docker > /dev/null
         if [ $? -ne 0 ]; then
-            echo "ERROR: Please install docker before run install script."
-            exit
+                echo "ERROR: Please install docker before run install script."
+                exit
         fi
         echo "2. Install tools"
-        mkdir -p /usr/local/bin/
-        cp tools/* /usr/local/bin/
+        wget {{ minio_address }}/acoreos/$ARCH/cni.tar
         tar xf cni.tar -C /
         echo "3. Load images"
-        for img in $(ls images/cos-*.tar); do
-                $(docker load -i $img | awk -F'[: \t]' '{print "docker tag "$4":"$5" "$4":latest"}')
-        done
-        ctr -n k8s.io i import images/pause.tar
-        ctr -n k8s.io i import images/busybox.tar
+        docker pull {{ registry_host }}/acoreos/cos-worknode:latest
+        wget {{ minio_address }}/acoreos/$ARCH/pause.tar
+        wget {{ minio_address }}/acoreos/$ARCH/busybox.tar
+        ctr -n k8s.io i import pause.tar
+        ctr -n k8s.io i import busybox.tar
         echo "4. Generate configs"
-        sed -e "s/REGISTRY_ADDR/$REGISTRY_ADDR/g" configs/config.toml > /etc/containerd/config.toml
-        sed -e "s/REGISTRY_ADDR/$REGISTRY_ADDR/g" configs/daemon.json > /etc/docker/daemon.json
+        wget {{ minio_address }}/acoreos/config.tar
+        tar -xf config.tar
+        sed -e "s/REGISTRY_ADDR/{{ registry_host }}/g" configs/config.toml > /etc/containerd/config.toml
+        sed -e "s/REGISTRY_ADDR/{{ registry_host }}/g" configs/daemon.json > /etc/docker/daemon.json
         cp configs/crictl.yaml /etc/crictl.yaml
         echo "5. Run containers"
         docker ps | grep cos- > /dev/null
-        if [ $? -eq 0 ]; then
+        if [ $? -eq 0 ]; then	
                 echo "Stop and remove running containers"
                 docker rm -f cos-master > /dev/null
                 docker rm -f cos-worknode > /dev/null
                 docker rm -f cos-dashboard > /dev/null
         fi
-        docker run -itd --restart=always --network=host --privileged=true --name cos-worknode -v /run/containerd/containerd.sock:/containerd/containerd.sock -v /run/flannel:/flannel -v /proxy-root:/proxy-root -v /etc/machine-id:/etc/machine-id cos-worknode:latest --api-servers={{ master_addr }} --hostname-override=node1 --enable-pod-ipam=1 --container-runtime-endpoint=unix:///containerd/containerd.sock --node-status-update-frequency=290 --sync-frequency=30000 > /dev/null
+        docker run -itd --restart=always --network=host --privileged=true --name cos-worknode -v /run/containerd/containerd.sock:/containerd/containerd.sock -v /run/flannel:/flannel -v /proxy-root:/proxy-root -v /etc/machine-id:/etc/machine-id {{ registry_host }}/acoreos/cos-worknode:latest --api-servers={{master_host}}:{{master_host}} --hostname-override=$NODE_NAME --enable-pod-ipam=1 --container-runtime-endpoint=unix:///containerd/containerd.sock --node-status-update-frequency=290 --sync-frequency=30000 > /dev/null
         if [ $? -ne 0 ]; then
                 echo "Run cos-worknode failed"
                 exit
         fi
         echo "Run cos-worknode success"
+        echo "Clean tar"
+        rm -rf cni.tar pause.tar busybox.tar config.tar config
       args:
         executable: /bin/bash
       register: clusterinfo
